# Limpieza principal del corpus


### IMPORTACIÓN DE LIBRERÍAS Y CORPUS

In [2]:
import pandas as pd

In [3]:
corpus_raw = pd.read_csv("../../data/processed/dataset_Google-Maps-Reviews-Scraper.csv_clean.csv")

corpus_raw.head(20)

,lugar,texto,calificacion,categoria,fuente,idioma_comentario,comentarios_espanol,emojis
0,Playa Manuel Antonio,Manuel Antonio Beach is absolutely stunning. T...,5.0,parque,google_maps,en,La playa de Manuel Antonio es absolutamente im...,NaN
1,Playa Manuel Antonio,Una de las dos playas que están separadas en e...,5.0,parque,google_maps,es,Una de las dos playas que están separadas en e...,😊
2,Playa Manuel Antonio,Plage exceptionnelle accessible uniquement en ...,5.0,parque,google_maps,fr,Playa excepcional a la que sólo se puede acced...,NaN
3,Playa Manuel Antonio,For any tourist or even locals MAB is incredib...,5.0,parque,google_maps,en,"Para cualquier turista o incluso local, MAB es...",NaN
4,Playa Manuel Antonio,"Jolie plage mais pas la plus belle su pays, il...",4.0,parque,google_maps,fr,"Bonita playa pero no la más bonita del país, h...",NaN
5,Playa Manuel Antonio,Really beautiful beach. But watch out for the ...,5.0,parque,google_maps,en,Playa realmente hermosa. Pero ten cuidado con ...,NaN
6,Playa Manuel Antonio,Me encantó el agua súper transparente habían p...,5.0,parque,google_maps,es,Me encantó el agua súper transparente habían p...,NaN
7,Playa Manuel Antonio,Beautifull beaches on this natural Park. Speci...,5.0,parque,google_maps,en,Hermosas playas en este parque natural. Coment...,NaN
8,Playa Manuel Antonio,Paraíso! Dentro de la reserva de encuentra est...,5.0,parque,google_maps,es,Paraíso! Dentro de la reserva de encuentra est...,NaN
9,Playa Manuel Antonio,"Hermosa playa, tener vudoadi con las corriente...",5.0,parque,google_maps,es,"Hermosa playa, tener vudoadi con las corriente...",NaN
10,Playa Manuel Antonio,Merveilleux 😊,5.0,parque,google_maps,unknown,Merveilleux,😊
11,Playa Manuel Antonio,The views from this beach are amazing. I was t...,5.0,parque,google_maps,en,Las vistas desde esta playa son increíbles. Me...,NaN
12,Playa Manuel Antonio,This beach is highly recommended. It’s very re...,5.0,parque,google_maps,en,Esta playa es muy recomendable. Es muy relajan...,NaN
13,Playa Manuel Antonio,Manuel Antonio csodás hely! Gyönyörű az óceánp...,5.0,parque,google_maps,hu,¡Manuel Antonio es un lugar maravilloso! ¡La c...,NaN
14,Playa Manuel Antonio,"Increíble playa para recordar y recordar, herm...",5.0,parque,google_maps,es,"Increíble playa para recordar y recordar, herm...",NaN
15,Playa Manuel Antonio,"Top 5 besch of our lifetime, after hawaii",5.0,parque,google_maps,en,"Los 5 mejores besch de nuestra vida, después d...",NaN
16,Playa Manuel Antonio,"Um an den Strand zu kommen, muss man ein Ticke...",1.0,parque,google_maps,de,Para llegar a la playa hay que comprar online ...,NaN
17,Playa Manuel Antonio,Plage de Manuel Antonio absolument magnifique ...,5.0,parque,google_maps,fr,¡Absolutamente hermosa playa de Manuel Antonio...,NaN
18,Playa Manuel Antonio,Best on the trip.,5.0,parque,google_maps,en,Lo mejor del viaje.,NaN
19,Playa Manuel Antonio,"Si vas al Parque Nacional Manuel Antonio, no o...",5.0,parque,google_maps,es,"Si vas al Parque Nacional Manuel Antonio, no o...",NaN

### LIMPIEZA DEL CORPUS

In [4]:
# IMPORTAMOS LAS FUNCIONES

from limpieza import (
    filtrar_unknown,
    aplicar_limpieza
)

In [5]:
corpus = filtrar_unknown(corpus_raw)

print(f'Comentarios totales   : {len(corpus_raw)}')
print(f'Comentarios unknown   : {len(corpus_raw) - len(corpus)}')
print(f'Comentarios a analizar: {len(corpus)}')

Comentarios totales   : 1281
Comentarios unknown   : 76
Comentarios a analizar: 1205

In [6]:
corpus.head(20)

,lugar,texto,calificacion,categoria,fuente,idioma_comentario,comentarios_espanol,emojis
0,Playa Manuel Antonio,Manuel Antonio Beach is absolutely stunning. T...,5.0,parque,google_maps,en,La playa de Manuel Antonio es absolutamente im...,NaN
1,Playa Manuel Antonio,Una de las dos playas que están separadas en e...,5.0,parque,google_maps,es,Una de las dos playas que están separadas en e...,😊
2,Playa Manuel Antonio,Plage exceptionnelle accessible uniquement en ...,5.0,parque,google_maps,fr,Playa excepcional a la que sólo se puede acced...,NaN
3,Playa Manuel Antonio,For any tourist or even locals MAB is incredib...,5.0,parque,google_maps,en,"Para cualquier turista o incluso local, MAB es...",NaN
4,Playa Manuel Antonio,"Jolie plage mais pas la plus belle su pays, il...",4.0,parque,google_maps,fr,"Bonita playa pero no la más bonita del país, h...",NaN
5,Playa Manuel Antonio,Really beautiful beach. But watch out for the ...,5.0,parque,google_maps,en,Playa realmente hermosa. Pero ten cuidado con ...,NaN
6,Playa Manuel Antonio,Me encantó el agua súper transparente habían p...,5.0,parque,google_maps,es,Me encantó el agua súper transparente habían p...,NaN
7,Playa Manuel Antonio,Beautifull beaches on this natural Park. Speci...,5.0,parque,google_maps,en,Hermosas playas en este parque natural. Coment...,NaN
8,Playa Manuel Antonio,Paraíso! Dentro de la reserva de encuentra est...,5.0,parque,google_maps,es,Paraíso! Dentro de la reserva de encuentra est...,NaN
9,Playa Manuel Antonio,"Hermosa playa, tener vudoadi con las corriente...",5.0,parque,google_maps,es,"Hermosa playa, tener vudoadi con las corriente...",NaN
10,Playa Manuel Antonio,The views from this beach are amazing. I was t...,5.0,parque,google_maps,en,Las vistas desde esta playa son increíbles. Me...,NaN
11,Playa Manuel Antonio,This beach is highly recommended. It’s very re...,5.0,parque,google_maps,en,Esta playa es muy recomendable. Es muy relajan...,NaN
12,Playa Manuel Antonio,Manuel Antonio csodás hely! Gyönyörű az óceánp...,5.0,parque,google_maps,hu,¡Manuel Antonio es un lugar maravilloso! ¡La c...,NaN
13,Playa Manuel Antonio,"Increíble playa para recordar y recordar, herm...",5.0,parque,google_maps,es,"Increíble playa para recordar y recordar, herm...",NaN
14,Playa Manuel Antonio,"Top 5 besch of our lifetime, after hawaii",5.0,parque,google_maps,en,"Los 5 mejores besch de nuestra vida, después d...",NaN
15,Playa Manuel Antonio,"Um an den Strand zu kommen, muss man ein Ticke...",1.0,parque,google_maps,de,Para llegar a la playa hay que comprar online ...,NaN
16,Playa Manuel Antonio,Plage de Manuel Antonio absolument magnifique ...,5.0,parque,google_maps,fr,¡Absolutamente hermosa playa de Manuel Antonio...,NaN
17,Playa Manuel Antonio,Best on the trip.,5.0,parque,google_maps,en,Lo mejor del viaje.,NaN
18,Playa Manuel Antonio,"Si vas al Parque Nacional Manuel Antonio, no o...",5.0,parque,google_maps,es,"Si vas al Parque Nacional Manuel Antonio, no o...",NaN
19,Playa Manuel Antonio,"Muy bonita playa, agua calentita y bien clarit...",5.0,parque,google_maps,es,"Muy bonita playa, agua calentita y bien clarit...",NaN

In [12]:
# CORPUS SIN LOS COMENTARIOS EN CATEGORÍA 'UNKNOWN'

corpus_comentarios = pd.DataFrame(corpus)
corpus_comentarios.to_csv('../../data/processed/corpus_Google-Maps-Reviews.csv', index=False)

print(f'Archivo guardado: corpus_Google-Maps-Reviews.csv')

Archivo guardado: corpus_Google-Maps-Reviews.csv

In [7]:
extras = set()

todas_las_palabras, stop_words = aplicar_limpieza(corpus, extras_stopwords=extras)

print(f'Total palabras procesadas: {len(todas_las_palabras)}')
print(f'Vocabulario único        : {len(set(todas_las_palabras))}')

Total palabras procesadas: 26166
Vocabulario único        : 5592

In [9]:
# CSV CON LAS PALABRAS MÁS REPETIDAS DEL CORPUS

comentarios_procesados = pd.DataFrame(todas_las_palabras, columns=['palabras'])
comentarios_procesados.to_csv('../../data/processed/corpus_palabras.csv', index=False)

print(f'Archivo guardado: corpus_palabras.csv')
print(f'Total filas: {len(comentarios_procesados)}')

Archivo guardado: corpus_palabras.csv
Total filas: 26166