# POS TAGGING - TurisPOS

## Manjejo de datos







### Importación de librerías

In [1]:
import pandas as pd

### CARGA y VERIFICACIÓN DE LOS DATOS

In [2]:
corpus_raw = pd.read_csv("../../data/raw/dataset_Google-Maps-Reviews-Scraper.csv")

In [3]:
corpus_raw.head(15)

,title,url,stars,name,reviewUrl,text
0,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Manuel Antonio Beach is absolutely stunning. T...
1,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Una de las dos playas que están separadas en e...
2,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Plage exceptionnelle accessible uniquement en ...
3,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,For any tourist or even locals MAB is incredib...
4,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,4.0,NaN,NaN,"Jolie plage mais pas la plus belle su pays, il..."
5,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,1.0,NaN,NaN,NaN
6,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Really beautiful beach. But watch out for the ...
7,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,NaN
8,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Me encantó el agua súper transparente habían p...
9,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Beautifull beaches on this natural Park. Speci...
10,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Paraíso! Dentro de la reserva de encuentra est...
11,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,NaN
12,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,"Hermosa playa, tener vudoadi con las corriente..."
13,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,NaN
14,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,NaN

### VER LA COMPOSICIÓN DE LOS DATOS

In [4]:
# ── 2. Verificar nulos ────────────────────────────────────────
print("=== VALORES NULOS ===")
nulos = pd.DataFrame({
    'nulos':      corpus_raw.isnull().sum(),
    'porcentaje': (corpus_raw.isnull().sum() / len(corpus_raw) * 100).round(2)
})
print(nulos[nulos['nulos'] > 0])   # solo columnas con nulos
print(f"\nTotal filas: {len(corpus_raw)}")

=== VALORES NULOS ===
           nulos  porcentaje
stars         45        2.21
name        2036      100.00
reviewUrl   2036      100.00
text         755       37.08

Total filas: 2036

In [5]:
# ── 4. Vista rápida por columna ───────────────────────────────
print("=== RESUMEN POR COLUMNA ===")
for col in corpus_raw.columns:
    print(f"\n▸ {col}")
    print(f"  Tipo     : {corpus_raw[col].dtype}")
    print(f"  Únicos   : {corpus_raw[col].nunique()}")
    print(f"  Nulos    : {corpus_raw[col].isnull().sum()}")
    if corpus_raw[col].dtype == 'object':
        print(f"  Ejemplo  : {corpus_raw[col].dropna().iloc[0] if not corpus_raw[col].dropna().empty else 'N/A'}")
    else:
        print(f"  Min/Max  : {corpus_raw[col].min()} / {corpus_raw[col].max()}")

=== RESUMEN POR COLUMNA ===

▸ title
  Tipo     : str
  Únicos   : 9
  Nulos    : 0
  Min/Max  : Catarata Río Fortuna / Restaurante Mi Finca

▸ url
  Tipo     : str
  Únicos   : 9
  Nulos    : 0
  Min/Max  : https://www.google.com/maps/search/?api=1&query=Catarata%20R%C3%ADo%20Fortuna&query_place_id=ChIJqyZY2rQNoI8RJqC3wUqtxgM / https://www.google.com/maps/search/?api=1&query=Restaurante%20Mi%20Finca&query_place_id=ChIJdYApioD0n48RduPJ14zhJXM

▸ stars
  Tipo     : float64
  Únicos   : 5
  Nulos    : 45
  Min/Max  : 1.0 / 5.0

▸ name
  Tipo     : float64
  Únicos   : 0
  Nulos    : 2036
  Min/Max  : nan / nan

▸ reviewUrl
  Tipo     : float64
  Únicos   : 0
  Nulos    : 2036
  Min/Max  : nan / nan

▸ text
  Tipo     : str
  Únicos   : 1272
  Nulos    : 755
  Min/Max  : -The resort itself and it's ponds+ gardening are A++ level. Really amazing with a lot of attention to details.
- Location and views are amazing.
- the rooms are mid for Western standards but big and functional.
- the food is varied but mid, expensive with ok service.

My family of 4 enjoyed this resort / 🚨HONEST REVIEW & TIP
💫Waterfall was 100/10. A must see in La Fortuna.
🩴TIP: Watershoes is a MUST to be able to get down to the water, swim and take photos. Not possible without watershoes.
📅Went first week of May

In [6]:
# CANTIDAD DE VECES QUE APARECEN LOS DESTINOS

frecuencia = corpus_raw['title'].value_counts().reset_index()
frecuencia.columns = ['title', 'cantidad']
frecuencia['porcentaje'] = (frecuencia['cantidad'] / len(corpus_raw) * 100).round(2)

print(f"Títulos únicos: {corpus_raw['title'].nunique()}\n")
print(frecuencia.to_string(index=False))

Títulos únicos: 9

                       title  cantidad  porcentaje
        Playa Manuel Antonio       250       12.28
          El Yugo de Mi Tata       250       12.28
              Playa Chiquita       250       12.28
        Restaurante Mi Finca       250       12.28
    Monteverde Country Lodge       250       12.28
        Catarata Río Fortuna       250       12.28
Hotel Los Lagos Spa & Resort       250       12.28
       Restaurante Fortuneño       250       12.28
     Corcovado National Park        36        1.77

### QUITAR CONTENIDO DE DATOS NULOS

In [7]:
corpus_raw = corpus_raw.dropna(subset=['text'])

print(f"Filas restantes: {len(corpus_raw)}")

Filas restantes: 1281

In [8]:
corpus_raw.head(20)

,title,url,stars,name,reviewUrl,text
0,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Manuel Antonio Beach is absolutely stunning. T...
1,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Una de las dos playas que están separadas en e...
2,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Plage exceptionnelle accessible uniquement en ...
3,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,For any tourist or even locals MAB is incredib...
4,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,4.0,NaN,NaN,"Jolie plage mais pas la plus belle su pays, il..."
6,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Really beautiful beach. But watch out for the ...
8,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Me encantó el agua súper transparente habían p...
9,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Beautifull beaches on this natural Park. Speci...
10,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Paraíso! Dentro de la reserva de encuentra est...
12,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,"Hermosa playa, tener vudoadi con las corriente..."
15,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Merveilleux 😊
16,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,The views from this beach are amazing. I was t...
18,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,This beach is highly recommended. It’s very re...
20,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Manuel Antonio csodás hely! Gyönyörű az óceánp...
22,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,"Increíble playa para recordar y recordar, herm..."
23,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,"Top 5 besch of our lifetime, after hawaii"
24,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,1.0,NaN,NaN,"Um an den Strand zu kommen, muss man ein Ticke..."
25,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Plage de Manuel Antonio absolument magnifique ...
26,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,Best on the trip.
27,Playa Manuel Antonio,https://www.google.com/maps/search/?api=1&quer...,5.0,NaN,NaN,"Si vas al Parque Nacional Manuel Antonio, no o..."

### ASIGNAR LAS CATEGORÍAS A CADA LUGAR

In [14]:
# Diccionario de categorías por lugar
categorias = {
    'Playa Manuel Antonio'       : 'parque',
    'El Yugo de Mi Tata'         : 'restaurante',
    'Playa Chiquita'             : 'parque',
    'Restaurante Mi Finca'       : 'restaurante',
    'Monteverde Country Lodge'   : 'alojamiento',
    'Catarata Río Fortuna'       : 'parque',
    'Hotel Los Lagos Spa & Resort': 'alojamiento',
    'Restaurante Fortuneño'      : 'restaurante',
    'Corcovado National Park'    : 'parque',
}

In [15]:
# CORPUS CON SUS RESPECTIVAS CATEGORÍAS DE LUGAR
corpus_clean = pd.DataFrame({
    'lugar'        : corpus_raw['title'].str.strip(),
    'texto'        : corpus_raw['text'],
    'calificacion' : corpus_raw['stars'],
    'categoria'    : corpus_raw['title'].map(categorias),
    'fuente'       : 'google_maps'
})


corpus_clean.head(15)

,lugar,texto,calificacion,categoria,fuente
0,Playa Manuel Antonio,Manuel Antonio Beach is absolutely stunning. T...,5.0,parque,google_maps
1,Playa Manuel Antonio,Una de las dos playas que están separadas en e...,5.0,parque,google_maps
2,Playa Manuel Antonio,Plage exceptionnelle accessible uniquement en ...,5.0,parque,google_maps
3,Playa Manuel Antonio,For any tourist or even locals MAB is incredib...,5.0,parque,google_maps
4,Playa Manuel Antonio,"Jolie plage mais pas la plus belle su pays, il...",4.0,parque,google_maps
6,Playa Manuel Antonio,Really beautiful beach. But watch out for the ...,5.0,parque,google_maps
8,Playa Manuel Antonio,Me encantó el agua súper transparente habían p...,5.0,parque,google_maps
9,Playa Manuel Antonio,Beautifull beaches on this natural Park. Speci...,5.0,parque,google_maps
10,Playa Manuel Antonio,Paraíso! Dentro de la reserva de encuentra est...,5.0,parque,google_maps
12,Playa Manuel Antonio,"Hermosa playa, tener vudoadi con las corriente...",5.0,parque,google_maps
15,Playa Manuel Antonio,Merveilleux 😊,5.0,parque,google_maps
16,Playa Manuel Antonio,The views from this beach are amazing. I was t...,5.0,parque,google_maps
18,Playa Manuel Antonio,This beach is highly recommended. It’s very re...,5.0,parque,google_maps
20,Playa Manuel Antonio,Manuel Antonio csodás hely! Gyönyörű az óceánp...,5.0,parque,google_maps
22,Playa Manuel Antonio,"Increíble playa para recordar y recordar, herm...",5.0,parque,google_maps

### TRADUCCIÓN DE COMENTARIOS AL ESPAÑOL

In [21]:
from langdetect import detect
from langdetect.lang_detect_exception import LangDetectException
from deep_translator import GoogleTranslator

In [22]:
# IDENTIFICA EL IDIOMA DEL COMENTARIO
# SI NO LO PUEDE DETECTAR LO CATEGORIZA COMO 'UNKNOWN'
def idioma_confiable(texto):
    if pd.isna(texto) or len(texto.split()) < 3:
        return "unknown"
    try:
        return detect(texto)
    except LangDetectException:
        return "unknown"

In [23]:
# AGREGA EL IDIOMA DETECTADO EN UNA NUEVA COLUMNA Y HACE UN CONTEO DE LOS IDIOMAS PRESENTES

corpus_clean["idioma_comentario"] = corpus_clean["texto"].apply(idioma_confiable)
corpus_clean["idioma_comentario"].value_counts()

idioma_comentario
en         520
es         460
de          88
unknown     76
fr          60
nl          21
pt          15
he           9
it           6
ca           5
ru           5
pl           3
hu           2
sv           2
tl           1
af           1
sl           1
sk           1
so           1
no           1
ro           1
cs           1
ko           1
Name: count, dtype: int64

In [24]:
# FUNCIÓN PARA TRADUCIR EL TEXTO ORIGINAL AL ESPAÑOL
translator = GoogleTranslator(source="auto", target="es")

def traducir_texto(texto, idioma):
    if pd.isna(texto) or texto.strip() == "":
        return texto
    if idioma in ["es", "unknown"]:
        return texto
    try:
        return translator.translate(texto)
    except:
        return texto

In [25]:
# AGREGA EL COMENTARIO YA TRADUCIDO AL CORPUS EN UNA NUEVA COLUMNA
# NO SE MODIFICA EL COMENTARIO ORIGINAL

corpus_clean["comentarios_espanol"] = corpus_clean.apply(
    lambda row: traducir_texto(row["texto"], row["idioma_comentario"]), axis=1
)

In [28]:
# SEPARAMOS LOS EMOJIS DEL COMENTARIO

import re

def extraer_emojis(texto):
    if pd.isna(texto):
        return ""
    emoji_pattern = re.compile("["
        u"\U0001F600-\U0001F64F"  # emoticonos
        u"\U0001F300-\U0001F5FF"  # símbolos y pictogramas
        u"\U0001F680-\U0001F6FF"  # transporte y mapas
        u"\U0001F1E0-\U0001F1FF"  # banderas
        u"\U00002700-\U000027BF"  # dingbats
        u"\U0001F900-\U0001F9FF"  # símbolos adicionales
        "]+", flags=re.UNICODE)
    return " ".join(emoji_pattern.findall(texto))

def quitar_emojis(texto):
    if pd.isna(texto):
        return texto
    emoji_pattern = re.compile("["
        u"\U0001F600-\U0001F64F"
        u"\U0001F300-\U0001F5FF"
        u"\U0001F680-\U0001F6FF"
        u"\U0001F1E0-\U0001F1FF"
        u"\U00002700-\U000027BF"
        u"\U0001F900-\U0001F9FF"
        "]+", flags=re.UNICODE)
    return emoji_pattern.sub("", texto).strip()


# CADA EMOJI SE COLOCA EN UNA NUEVA COLUMNA

corpus_clean["emojis"] = corpus_clean["comentarios_espanol"].apply(extraer_emojis)
corpus_clean["comentarios_espanol"] = corpus_clean["comentarios_espanol"].apply(quitar_emojis)

In [29]:
corpus_clean.head(15)

,lugar,texto,calificacion,categoria,fuente,idioma_comentario,comentarios_espanol,emojis
0,Playa Manuel Antonio,Manuel Antonio Beach is absolutely stunning. T...,5.0,parque,google_maps,en,La playa de Manuel Antonio es absolutamente im...,
1,Playa Manuel Antonio,Una de las dos playas que están separadas en e...,5.0,parque,google_maps,es,Una de las dos playas que están separadas en e...,😊
2,Playa Manuel Antonio,Plage exceptionnelle accessible uniquement en ...,5.0,parque,google_maps,fr,Playa excepcional a la que sólo se puede acced...,
3,Playa Manuel Antonio,For any tourist or even locals MAB is incredib...,5.0,parque,google_maps,en,"Para cualquier turista o incluso local, MAB es...",
4,Playa Manuel Antonio,"Jolie plage mais pas la plus belle su pays, il...",4.0,parque,google_maps,fr,"Bonita playa pero no la más bonita del país, h...",
6,Playa Manuel Antonio,Really beautiful beach. But watch out for the ...,5.0,parque,google_maps,en,Playa realmente hermosa. Pero ten cuidado con ...,
8,Playa Manuel Antonio,Me encantó el agua súper transparente habían p...,5.0,parque,google_maps,es,Me encantó el agua súper transparente habían p...,
9,Playa Manuel Antonio,Beautifull beaches on this natural Park. Speci...,5.0,parque,google_maps,en,Hermosas playas en este parque natural. Coment...,
10,Playa Manuel Antonio,Paraíso! Dentro de la reserva de encuentra est...,5.0,parque,google_maps,es,Paraíso! Dentro de la reserva de encuentra est...,
12,Playa Manuel Antonio,"Hermosa playa, tener vudoadi con las corriente...",5.0,parque,google_maps,es,"Hermosa playa, tener vudoadi con las corriente...",
15,Playa Manuel Antonio,Merveilleux 😊,5.0,parque,google_maps,unknown,Merveilleux,😊
16,Playa Manuel Antonio,The views from this beach are amazing. I was t...,5.0,parque,google_maps,en,Las vistas desde esta playa son increíbles. Me...,
18,Playa Manuel Antonio,This beach is highly recommended. It’s very re...,5.0,parque,google_maps,en,Esta playa es muy recomendable. Es muy relajan...,
20,Playa Manuel Antonio,Manuel Antonio csodás hely! Gyönyörű az óceánp...,5.0,parque,google_maps,hu,¡Manuel Antonio es un lugar maravilloso! ¡La c...,
22,Playa Manuel Antonio,"Increíble playa para recordar y recordar, herm...",5.0,parque,google_maps,es,"Increíble playa para recordar y recordar, herm...",

In [36]:
# GUARDAMOS EL CORPUS NUEVO EN LA RUTA DETERMINADA

ruta_processed = "../../data/processed/dataset_Google-Maps-Reviews-Scraper.csv_clean.csv"

corpus_clean.to_csv(ruta_processed, index=False)
print("Archivo limpio guardado en data/processed")

Archivo limpio guardado en data/processed